// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
    const { Sequelize } = sequelize;
    // This section contains the fields of your model, mapped to your table's columns.
    // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
    const Product = sequelize.define(
        "product",
        {
            id: {
                type: DataTypes.INTEGER,
                primaryKey: true,
                allowNull: false,
                autoIncrement: true,
            },
            name: {
                type: DataTypes.STRING(255),
                allowNull: false,
            },
            image: {
                type: DataTypes.STRING(255),
            },
            code: {
                type: DataTypes.STRING(255),
                allowNull: false,
            },
            reference: {
                type: DataTypes.STRING(255),
                allowNull: false,
            },
            description: {
                type: DataTypes.TEXT,
                allowNull: false,
            },
            technicalDescription: {
                type: DataTypes.TEXT,
            },
            file: {
                type: DataTypes.STRING(255),
            },
            minimumOrderQuantity: {
                type: DataTypes.INTEGER,
            },
            orderQuantityStep: {
                type: DataTypes.INTEGER,
            },
        },
        {
            tableName: "product",
            timestamps: false,
        },
    );

    // This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
    Product.associate = (models) => {
        // Product.belongsTo(models.productSubCategory, {
		// 	foreignKey: "productSubCategoryId",
		// });

		// Product.hasMany(models.packaging);
    };

    return Product;
};
