// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models
module.exports = (sequelize, DataTypes) => {
	const { Sequelize } = sequelize;
	// This section contains the fields of your model, mapped to your table's columns.
	// Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
	const Registration = sequelize.define(
		"registration",
		{
			id: {
				type: DataTypes.INTEGER,
				primaryKey: true,
				allowNull: false,
				autoIncrement: true,
			},
			status: {
				type: DataTypes.ENUM(
					"REGISTERED",
					"UNDER_RENEWAL",
					"ELIGIBLE_FOR_IMPORT_WITH_LETTER",
					"REGISTRATION_NOT_REQUIRED_OR_ELIGIBLE_FOR_IMPORT",
					"PREPARING_SUBMISSION",
					"SUBMITTED_OR_PENDING_REGISTRATION",
					"NOT_REGISTERED",
					"NOT_REGISTERED_OR_IMPORT_REQUIREMENT_STATUS_UNKNOWN",
				),
				allowNull: false,
			},
			price: {
				type: DataTypes.DECIMAL(11, 2),
				allowNull: false,
			},
            discount: {
				type: DataTypes.INTEGER,
			},
            remarks: {
				type: DataTypes.TEXT,
			},
		},
		{
			tableName: "registration",
			timestamps: false,
		},
	);

	// This section contains the relationships for this model. See: https://docs.forestadmin.com/documentation/v/v6/reference-guide/relationships#adding-relationships.
	Registration.associate = (models) => {
		// Registration.belongsTo(models.distributor, {
		// 	foreignKey: "distributorId",
		// });

		// Registration.belongsTo(models.country, {
		// 	foreignKey: "countryId",
		// });

		Registration.belongsTo(models.product, {
			foreignKey: "productId",
		});

    Registration.belongsTo(models.label, {
			targetKey: "id",
			as: "label",
		});

    Registration.belongsTo(models.label, {
			targetKey: "id",
			as: "secondaryPackagingLabel",
		});

    Registration.belongsTo(models.label, {
			targetKey: "id",
			as: "masterCartonLabel",
		});

        Registration.belongsTo(models.label, {
			targetKey: "id",
			as: "shippingCartonLabel",
		});

    Registration.belongsTo(models.label, {
			targetKey: "id",
			as: "otherLabel",
		});

		Registration.belongsTo(models.label, {
			targetKey: "id",
			as: "reworkLabel",
		});

	// 	Registration.belongsTo(models.ifu, {
	// 		foreignKey: "ifuId",
	// 	});
	 };

	return Registration;
};
